package ca.uvic.seng330.assn3.controller;

public enum ViewType {
  LOGIN,
  CREATE_DEVICE,
  HUB_BASIC,
  HUB_ADMIN,
  DEVICE_VIEW,
  MANAGE_USERS,
  MANAGE_DEVICES,
  MANAGE_NOTIFICATIONS,
  MANAGE_ROOMS,
  SELECT_DEVICES,
  SEE_NOTIFICATIONS
}
